In [10]:
# https://adventofcode.com/2021/day/4
import numpy as np
import re

In [ ]:
## load input + all boards data.

#with open("day04_sample.txt") as f:
with open("day04.txt") as f:
    lines = f.readlines()

# number to be called.
numbers = lines[0].strip().split(',')
numbers = [int(n) for n in numbers]

# all boards.
boards  = lines[2:]

board_size = 5
n_board = int( (len(boards) - board_size) / (board_size + 1) ) + 1

In [12]:
def get_board(boards, n):
    board_ = boards[n * (board_size + 1): (n + 1) * (board_size + 1) - 1]
    board = [re.findall('[0-9]+', board_[r]) for r in range(board_size)]
    return np.array(board, dtype='int')


def when_to_complete_line(x, numbers):
    x_ = [0 if n in numbers else 1 for n in x]
    if np.sum(x_) == 0:
        called = [numbers.index(n) for n in x]
        t_complete = np.max(called) 
    else:
        t_complete = 1000000
    return t_complete


def when_to_complete_board(board):
    t_r = [when_to_complete_line(board[:, i], numbers) for i in range(board_size)]
    t_c = [when_to_complete_line(board[i, :], numbers) for i in range(board_size)]
    return np.min(t_r + t_c)


def get_final_score(t_complete):
    unmarked_numbers = [0 if i in numbers[:t_complete+1] else i for i in board.reshape(board_size * board_size)]
    return np.sum(unmarked_numbers) * numbers[t_complete]

In [18]:
## part 1.
#win_board = np.argmin([when_to_complete_board(get_board(boards, n)) for n in range(n_board)])
## part 2.
win_board = np.argmax([when_to_complete_board(get_board(boards, n)) for n in range(n_board)])

board       = get_board(boards, win_board)
t_complete  = when_to_complete_board(board)
win_number  = numbers[t_complete]
final_score = get_final_score(t_complete)

print(f'{board} \n wins when {win_number} (n={t_complete}) is called.')
print(f'final score: {final_score}')

[[98 75 47  9 18]
 [44 97 26 73 64]
 [62 99 13 43  0]
 [51 37 10 74 94]
 [35 68 22 76 83]] 
 wins when 35 (n=83) is called.
final score: 12635
