In [1]:
import os
import re

import numpy as np

In [2]:
def get_n_balls(record, color):
    n = re.findall('(\d+) '+color, record)
    n_balls = 0
    if len(n)>0:
        n_balls = int(n[0])
    return n_balls

In [8]:
with open("input1_.txt") as f:
    lines = f.read().strip().split('\n')

data = []
for line in lines:
    print(line)
    
    n_game_, records_ = line.split(':')
    n_game = int(n_game_.replace('Game ', ''))
    records_ = records_.split(';')
    
    n_balls = []
    for record_ in records_:
        print(record_)
        n_balls_ = (
            get_n_balls(record_, 'red'), 
            get_n_balls(record_, 'green'), 
            get_n_balls(record_, 'blue')
        )
        n_balls.append(n_balls_)
    
    data.append(np.array(n_balls))

Game 1: 3 blue, 4 red; 1 red, 2 green, 6 blue; 2 green
 3 blue, 4 red
 1 red, 2 green, 6 blue
 2 green
Game 2: 1 blue, 2 green; 3 green, 4 blue, 1 red; 1 green, 1 blue
 1 blue, 2 green
 3 green, 4 blue, 1 red
 1 green, 1 blue
Game 3: 8 green, 6 blue, 20 red; 5 blue, 4 red, 13 green; 5 green, 1 red
 8 green, 6 blue, 20 red
 5 blue, 4 red, 13 green
 5 green, 1 red
Game 4: 1 green, 3 red, 6 blue; 3 green, 6 red; 3 green, 15 blue, 14 red
 1 green, 3 red, 6 blue
 3 green, 6 red
 3 green, 15 blue, 14 red
Game 5: 6 red, 1 blue, 3 green; 2 blue, 1 red, 2 green
 6 red, 1 blue, 3 green
 2 blue, 1 red, 2 green


In [9]:
data

[array([[4, 0, 3],
        [1, 2, 6],
        [0, 2, 0]]),
 array([[0, 2, 1],
        [1, 3, 4],
        [0, 1, 1]]),
 array([[20,  8,  6],
        [ 4, 13,  5],
        [ 1,  5,  0]]),
 array([[ 3,  1,  6],
        [ 6,  3,  0],
        [14,  3, 15]]),
 array([[6, 3, 1],
        [1, 2, 2]])]

In [5]:
np.array(n_balls)

array([[4, 0, 3],
       [1, 2, 6],
       [0, 2, 0]])